"""Schemas package - Pydantic schemas for request/response validation."""

from app.schemas.announcement import (
    AnnouncementCreate,
    AnnouncementListItem,
    AnnouncementListResponse,
    AnnouncementResponse,
    AnnouncementUpdate,
    AuthorResponse,
)
from app.schemas.auth import (
    ErrorResponse,
    LoginRequest,
    LoginResponse,
    RefreshTokenRequest,
    RefreshTokenResponse,
    TenantRegisterRequest,
    TenantRegisterResponse,
    UserProfileResponse,
)
from app.schemas.exam import (
    BulkGradeCreate,
    BulkGradeItem,
    BulkGradeResponse,
    ClassAnalytics,
    ExamCreate,
    ExamListItem,
    ExamListResponse,
    ExamResponse,
    ExamResult,
    ExamUpdate,
    GradeAnalyticsResponse,
    GradeCreate,
    GradeListItem,
    GradeListResponse,
    GradeResponse,
    GradeUpdate,
    ReportCardResponse,
    SubjectAnalytics,
    SubjectGrade,
)
from app.schemas.fee import (
    FeeCollectionReport,
    FeeCreate,
    FeeListItem,
    FeeListResponse,
    FeeResponse,
    FeeTypeSummary,
    FeeUpdate,
    PaymentRecord,
    PaymentResponse,
    PendingFeeListResponse,
    StudentFeeSummary,
)
from app.schemas.leave_request import (
    ApprovalAction,
    LeaveRequestCreate,
    LeaveRequestListItem,
    LeaveRequestListResponse,
    LeaveRequestResponse,
    LeaveRequestUpdate,
    PendingCountResponse,
    UserInfo,
)
from app.schemas.school import (
    ClassCreate,
    ClassListItem,
    ClassListResponse,
    ClassResponse,
    ClassUpdate,
    EnrolledStudentItem,
    EnrolledStudentsResponse,
    SectionCreate,
    SectionListItem,
    SectionListResponse,
    SectionResponse,
    SectionSummary,
    SectionUpdate,
    SubjectCreate,
    SubjectListItem,
    SubjectListResponse,
    SubjectResponse,
    SubjectSummary,
    SubjectUpdate,
    TeacherInfo,
)
from app.schemas.student import (
    AttendanceSummary,
    FeeItem,
    FeesSummary,
    GradeItem,
    StudentCreate,
    StudentInfo,
    StudentListItem,
    StudentListResponse,
    StudentProfileResponse,
    StudentResponse,
    StudentUpdate,
    UserProfileData,
    UserResponse,
)
from app.schemas.teacher import (
    ClassInfo,
    TeacherClassesResponse,
    TeacherCreate,
    TeacherListItem,
    TeacherListResponse,
    TeacherResponse,
    TeacherUpdate,
)
from app.schemas.timetable import (
    ClassTimetableResponse,
    ConflictCheckResponse,
    ConflictInfo,
    TeacherTimetableResponse,
    TimetableCreate,
    TimetableListItem,
    TimetableListResponse,
    TimetableResponse,
    TimetableUpdate,
)

__all__ = [
    # Announcement schemas
    "AnnouncementCreate",
    "AnnouncementListItem",
    "AnnouncementListResponse",
    "AnnouncementResponse",
    "AnnouncementUpdate",
    "AuthorResponse",
    # Auth schemas
    "ErrorResponse",
    "LoginRequest",
    "LoginResponse",
    "RefreshTokenRequest",
    "RefreshTokenResponse",
    "TenantRegisterRequest",
    "TenantRegisterResponse",
    "UserProfileResponse",
    # Exam schemas
    "ExamCreate",
    "ExamUpdate",
    "ExamResponse",
    "ExamListItem",
    "ExamListResponse",
    # Fee schemas
    "FeeCreate",
    "FeeUpdate",
    "FeeResponse",
    "FeeListItem",
    "FeeListResponse",
    "PaymentRecord",
    "PaymentResponse",
    "PendingFeeListResponse",
    "FeeCollectionReport",
    "FeeTypeSummary",
    "StudentFeeSummary",
    # Grade schemas
    "GradeCreate",
    "GradeUpdate",
    "GradeResponse",
    "GradeListItem",
    "GradeListResponse",
    "BulkGradeCreate",
    "BulkGradeItem",
    "BulkGradeResponse",
    # Leave request schemas
    "LeaveRequestCreate",
    "LeaveRequestUpdate",
    "LeaveRequestResponse",
    "LeaveRequestListItem",
    "LeaveRequestListResponse",
    "ApprovalAction",
    "PendingCountResponse",
    "UserInfo",
    # Report card schemas
    "SubjectGrade",
    "ExamResult",
    "ReportCardResponse",
    # Analytics schemas
    "SubjectAnalytics",
    "ClassAnalytics",
    "GradeAnalyticsResponse",
    # School schemas
    "ClassCreate",
    "ClassListItem",
    "ClassListResponse",
    "ClassResponse",
    "ClassUpdate",
    "EnrolledStudentItem",
    "EnrolledStudentsResponse",
    "SectionCreate",
    "SectionListItem",
    "SectionListResponse",
    "SectionResponse",
    "SectionSummary",
    "SectionUpdate",
    "SubjectCreate",
    "SubjectListItem",
    "SubjectListResponse",
    "SubjectResponse",
    "SubjectSummary",
    "SubjectUpdate",
    "TeacherInfo",
    # Student schemas
    "AttendanceSummary",
    "FeeItem",
    "FeesSummary",
    "GradeItem",
    "StudentCreate",
    "StudentInfo",
    "StudentListItem",
    "StudentListResponse",
    "StudentProfileResponse",
    "StudentResponse",
    "StudentUpdate",
    "UserProfileData",
    "UserResponse",
    # Teacher schemas
    "ClassInfo",
    "TeacherClassesResponse",
    "TeacherCreate",
    "TeacherListItem",
    "TeacherListResponse",
    "TeacherResponse",
    "TeacherUpdate",
    # Timetable schemas
    "TimetableCreate",
    "TimetableUpdate",
    "TimetableResponse",
    "TimetableListItem",
    "TimetableListResponse",
    "ConflictInfo",
    "ConflictCheckResponse",
    "ClassTimetableResponse",
    "TeacherTimetableResponse",
]
